name: Docker Image CI

on:
  push:
    branches: [ Production ]
  pull_request:
    branches: [ Production ]

jobs:

  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/server/backend/RAWebAPI

    steps:
    - name: Pull project down from github
      run: sudo git pull
            
    - name: Run Docker-Compose
      run: sudo docker-compose -f docker-compose.yml up -d --build
