name: Docker Image CI

on:
  push:
    branches: [ Production ]
  pull_request:
    branches: [ Production ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Pull project down from github
      run: git pull origin Production
      
    - name: Stop Docker
      run: docker stop backend
      
    - name: Build Docker
      run: docker build . -t backend
      
    - name: Run Docker
      run: docker run --rm -d -p 5000:5000 --name backend backend
