name: Docker Image CI

on:
  push:
    branches: [ Production ]
  pull_request:
    branches: [ Production ]

jobs:

  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/server/62597-backend/RAWebAPI

    steps:
    - name: Pull project down from github
      run: git pull origin Production
      
    - name: Stop Docker
      run: docker stop backendAPI
      
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag backendImage:$(date +%s)
      
    - name: Run Docker
      run: docker run --rm -d -p 5002:5002 --name backendAPI backendImage
